services:
    - type: web
      name: site-chales
      env: python
      buildCommand: pip install -r requirements.txt
      startCommand: gunicorn chale.wsgi:application
      envVars:
          - key: DJANGO_SETTINGS_MODULE
            value: chale.settings
          - key: PYTHON_VERSION
            value: 3.9
          - key: SECRET_KEY
            value:'django-insecure-+qd_!@v@m3u2+hefuyt-(^==h)p$lr-h-j+6z7#sg2&viejp67'
          - key: DEBUG
            value: False
