# Generated by Django 4.2.20 on 2025-04-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteChale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chale',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
